### ISSUE TITLE
i2cp config and tunnels info are missing

### ISSUE THREAD

**Issue by danrobi11** [knaccc/i2p-zero#28]
Noticed that theres no easy obvious way for users to be able to change the i2cp config.
Docker images are listening on 172.17.0.1  Need to be able to config i2cp in i2p-zero.
I cant find my tunnels info. A list of our active tunnels would be nice to have.
Also Cant find how to exclude slow peers. theres no: router.excludePeers=
How to exclude slow peers with i2p-zero?
Thanks!

**Comment by jtgrassie** [comment]
Do you mean something like: https://github.com/i2p-zero/i2p-zero/blob/master/README.md#list-all-tunnels-returns-json-string-containing-information-about-all-tunnels-currently-in-existence

**Comment by danrobi11** [comment]
I just tried a few command like: tunnel-control.sh all.list and tunnel-control.sh version and that doesnt work here. May be cuz im running the GUI?

**Comment by jtgrassie** [comment]
You can still use tunnel-control.sh even if you used the GUI to create your tunnels. https://github.com/i2p-zero/i2p-zero#tunnel-control

The GUI also has a tab called "Tunnels" which shows the tunnels and their status'.

**Comment by danrobi11** [comment]
yes i see it shows as 'open' doesnt say how many and how healthy they are
Doesnt work here for me: https://open.lbry.com/@Danrobi:b/cant-tunnel-control.sh-2020-03-21_18.00.16:5

**Comment by jtgrassie** [comment]
Your video just shows you don't know how to use the command line - you have to have the correct path to tunnel-control.sh, otherwise you will get a "command not found", like what is happening for you.

Your video also shows you didn't click the "Tunnels" tab in the GUI, which shows what tunnels are configured and their status.

Lastly please don't post videos in a bug tracker.

**Comment by danrobi11** [comment]
ok thx
